version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: mkdir junit
      - run: 
        when: always
        command: node_modules/.bin/mocha test --reporter mocha-junit-reporter
        environment: map[MOCHA_FILE:./junit/test-results.xml]
      - store_test_results:
        path: ./junit
      - store_artifacts:
        path: ./junit